# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
#    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: docker_apis_evoke
      MYSQL_USER: root
      MYSQL_PASSWORD: Akki143@
      MYSQL_ROOT_PASSWORD: root


